/**
 * profilepic.js
 *
 * Random AI profile picture generator
 *
 * Usage:
 * profilepic
 */

const axios = require("axios");
const fs = require("fs-extra");
const path = require("path");


const CACHE_DIR =
    path.join(__dirname, "cache", "profilepic");



module.exports.config = {

    name: "profilepic",

    version: "1.0.0",

    hasPermssion: 0,

    credits: "MrDeveloper",

    description:
        "Generate random high quality profile picture",

    usePrefix: true,

    commandCategory: "image",

    usages:
        "profilepic",

    cooldowns: 5

};



module.exports.run = async function({

    api,
    event

}) {


const {
    threadID,
    messageID
}=event;



try {


await fs.ensureDir(
    CACHE_DIR
);



const filePath =
path.join(
    CACHE_DIR,
    `profile_${Date.now()}.jpg`
);



/*
    This endpoint returns
    a direct image stream
*/

const imageURL =
"https://thispersondoesnotexist.com/";



const response =
await axios.get(

    imageURL,

    {

        responseType:"arraybuffer",

        timeout:30000,

        headers:{

            "User-Agent":
            "Mozilla/5.0"

        }

    }

);



const buffer =
Buffer.from(
    response.data
);



/*
    Validate response
*/

if(
    !buffer ||
    buffer.length < 10000
){

    throw new Error(
        "Invalid image received"
    );

}



await fs.writeFile(
    filePath,
    buffer
);



api.sendMessage(

{

body:

"🖤 Random AI Profile Picture\n\n"+
"✨ Generated by Mr Developer",

attachment:
fs.createReadStream(filePath)

},

threadID,


(err)=>{


fs.unlink(
    filePath
)
.catch(()=>{});


if(err)
console.log(
"send error:",
err
);


},


messageID


);



}

catch(err){


console.error(
"profilepic error:",
err.message
);



api.sendMessage(

"❌ Failed to fetch image. Try again.",

threadID,

messageID

);


}



};